In [45]:
import pandas as pd
import numpy as np

###`Q-1:` Write a program to create an empty series.

In [5]:
# code here
empty = pd.Series()

###`Q-2:` Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [7]:
# code here
def add(s1, s2):
  return s1 + s2

print(add(pd.Series([1,2,3,4]), pd.Series([1,2,3,4])))

0    2
1    4
2    6
3    8
dtype: int64

###`Q-3` Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [8]:
# code here
def compare(s1, s2):
  return s1[s1==s2]

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print(compare(s1,s2))

4    10
dtype: int64

###`Q-5.`Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.
```
series = pd.Series([1,2,'Python', 2.0, True, 100])
change to float type data
```
Note: Read about pd.to_numeric()

In [10]:

# code here
def change(s1, dt):
  s1.astype(dt)

Download data - https://drive.google.com/file/d/1LRhXwbEodeWXtzPhJCX0X9Lf_BECzvqb/view?usp=share_link
All Batsman runs series in IPL 2008 to 2022.

Below questions are based on this data.

###`Q-6` Find top 10 most run getter from the series.

In [31]:
# code here
df = pd.read_csv("https://drive.google.com/uc?id=1LRhXwbEodeWXtzPhJCX0X9Lf_BECzvqb")
df = df.set_index('batter')["batsman_run"]

In [33]:
df.sort_values( ascending=False).head(10)

batter
V Kohli           6634
S Dhawan          6244
DA Warner         5883
RG Sharma         5881
SK Raina          5536
AB de Villiers    5181
CH Gayle          4997
MS Dhoni          4978
RV Uthappa        4954
KD Karthik        4377
Name: batsman_run, dtype: int64

###`Q-7` No of players having runs above 3000

In [34]:
# code here
df[df>=3000]

batter
AB de Villiers    5181
AM Rahane         4074
AT Rayudu         4190
CH Gayle          4997
DA Warner         5883
F du Plessis      3403
G Gambhir         4217
KA Pollard        3437
KD Karthik        4377
KL Rahul          3895
MK Pandey         3657
MS Dhoni          4978
RG Sharma         5881
RV Uthappa        4954
S Dhawan          6244
SK Raina          5536
SR Watson         3880
SV Samson         3526
V Kohli           6634
YK Pathan         3222
Name: batsman_run, dtype: int64

###`Q-8` No of players having runs above mean value?

In [35]:
# code here
df[df> df.mean()].size

128

Download data - https://drive.google.com/file/d/1QZuZ5bypUInfVvarHACLAi8tXXHvb8xd/view?usp=share_link

file name - items.csv

###`Q-9`
    i. Read `items.csv` making `item_name` as index.
    ii. Show no of nan values
    ii. Item price is given in $, so convert it to rupees without currency symbol.
    iii. Make data type of newly made series as float.
    iv. Fill nan with mean of the series


How csv file looks

```
item_name	item_price
Chips and Fresh Tomato Salsa	$2.39
Izze	$3.39
Nantucket Nectar	$3.39
Chips and Tomatillo-Green Chili Salsa	$2.39
Chicken Bowl	$16.98

```

In [51]:
# code here

df = pd.read_csv("https://drive.google.com/uc?id=1QZuZ5bypUInfVvarHACLAi8tXXHvb8xd").set_index("item_name")["item_price"]
df = df.dropna()
df.isna().sum()

np.int64(0)

In [52]:

df.head()

item_name
Chips and Fresh Tomato Salsa              $2.39
Izze                                      $3.39
Nantucket Nectar                          $3.39
Chips and Tomatillo-Green Chili Salsa     $2.39
Chicken Bowl                             $16.98
Name: item_price, dtype: object

In [55]:
df = df.apply(lambda x: float(x[1:])*94.48 if pd.notna(x) else np.nan)

###`Q-10`:
    i. Find mean price
    ii. Find 30th and 6th percentile value
    iii. Plot Histogram on price with bin size 50
    iv. No of items price lies between [1000 to 2000]

In [56]:
# code here
print(f"Mean price: {df.mean()}")
print(f"30th percentile: {df.quantile(q=0.3)}")
print(f"6th percentile: {df.quantile(q=0.06)}")
df[df.between(1000,2000)]

Mean price: 705.1072157480315
30th percentile: 420.43600000000004
6th percentile: 118.10000000000001

item_name
Chicken Bowl          1604.2704
Chicken Bowl          1037.3904
Steak Burrito         1110.1400
Chicken Bowl          1062.9000
Chicken Burrito       1037.3904
                        ...
Steak Burrito         1110.1400
Veggie Burrito        1062.9000
Steak Burrito         1110.1400
Steak Burrito         1110.1400
Chicken Salad Bowl    1062.9000
Name: item_price, Length: 1066, dtype: float64